# Generated by Django 2.0.6 on 2018-06-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0007_auto_20180618_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='Pizzas', to='many_to_many.Toppings'),
        ),
    ]
